name: catalog_app
description: Простой учебный каталог продуктов на Flutter
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Тут никаких внешних пакетов — чтобы легко запустить.
  # Если захочешь later — можно добавить provider, intl и т.д.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
